// ABOUTME: Tests Google's key-set cache: an unknown kid costs one fetch per interval, a rotation is still found
// ABOUTME: A local key-set server counts fetches and an openssl key plays Google's signer, so no call reaches Google
//
// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (c) 2026 dravr.ai

#![cfg(feature = "google-iam")]
// Same allowances tests/iam_test.rs carries: an integration test is not
// covered by the lib's `cfg_attr(test, ...)`, and assertions are what these are.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::str_to_string
)]

use std::io::Write;
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use axum::extract::State;
use axum::http::header::CONTENT_TYPE;
use axum::http::StatusCode;
use axum::response::IntoResponse;
use axum::routing::get;
use axum::Router;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine;
use dravr_tronc::iam::{GoogleIdTokenVerifier, GoogleKeySet, IamError};
use futures::future::join_all;
use jsonwebtoken::{encode, Algorithm, EncodingKey, Header};
use reqwest::Client;
use serde::Serialize;
use serde_json::{json, Value};
use tokio::net::TcpListener;
use tokio::time::sleep;

/// The audience these tests pin against — shape-identical to a Cloud Run URL.
const AUDIENCE: &str = "https://example-service-abc123-nn.a.run.app";

/// The one caller the allowlisting tests expect.
const CALLER: &str = "caller@example-project.iam.gserviceaccount.com";

/// An interval no test outlives, so "inside the interval" never depends on timing.
const LONG_INTERVAL: Duration = Duration::from_secs(600);

/// What the stand-in key-set endpoint answers, and how often it was asked.
struct Published {
    response: Mutex<(StatusCode, String)>,
    fetches: AtomicUsize,
}

/// A local stand-in for Google's key-set endpoint.
struct KeySetServer {
    url: String,
    published: Arc<Published>,
}

impl KeySetServer {
    /// Serve `keys` as a JWK set at a fresh loopback address.
    async fn start(keys: &[Value]) -> Self {
        let published = Arc::new(Published {
            response: Mutex::new((StatusCode::OK, json!({ "keys": keys }).to_string())),
            fetches: AtomicUsize::new(0),
        });
        let listener = TcpListener::bind("127.0.0.1:0").await.expect("binds");
        let addr = listener.local_addr().expect("has an address");
        let app = Router::new()
            .route("/keys", get(answer))
            .with_state(Arc::clone(&published));
        tokio::spawn(async move { axum::serve(listener, app).await });
        Self {
            url: format!("http://{addr}/keys"),
            published,
        }
    }

    /// Replace what the endpoint answers from now on.
    fn publish(&self, status: StatusCode, body: String) {
        *self.published.response.lock().expect("lock") = (status, body);
    }

    /// How many times the endpoint has been fetched.
    fn fetches(&self) -> usize {
        self.published.fetches.load(Ordering::SeqCst)
    }

    /// A verifier for [`AUDIENCE`] reading this endpoint, refetching at most
    /// once per `interval`.
    fn verifier(&self, interval: Duration) -> GoogleIdTokenVerifier {
        GoogleIdTokenVerifier::with_key_set(
            AUDIENCE,
            GoogleKeySet::new(&self.url, Client::new()).with_min_refetch_interval(interval),
        )
    }
}

/// The endpoint's handler: count the fetch, answer what is published.
async fn answer(State(published): State<Arc<Published>>) -> impl IntoResponse {
    published.fetches.fetch_add(1, Ordering::SeqCst);
    let (status, body) = published.response.lock().expect("lock").clone();
    (status, [(CONTENT_TYPE, "application/json")], body)
}

/// The claims of an identity token, as Google mints them with `format=full`.
#[derive(Serialize)]
struct Claims {
    iss: &'static str,
    aud: &'static str,
    sub: &'static str,
    email: &'static str,
    email_verified: bool,
    exp: u64,
    iat: u64,
}

impl Claims {
    /// A token for [`AUDIENCE`] from [`CALLER`], valid for an hour.
    fn for_caller() -> Self {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("the clock is after 1970")
            .as_secs();
        Self {
            iss: "https://accounts.google.com",
            aud: AUDIENCE,
            sub: "115000000000000000001",
            email: CALLER,
            email_verified: true,
            exp: now + 3600,
            iat: now,
        }
    }
}

/// An RSA key playing one of Google's signing keys.
///
/// Generated by the `openssl` CLI, which every developer machine and CI runner
/// carries; no Rust crate this one depends on can generate an RSA key.
struct Signer {
    private_pem: String,
    modulus: String,
}

impl Signer {
    /// A fresh 2048-bit key.
    fn generate() -> Self {
        let generated = Command::new("openssl")
            .args([
                "genpkey",
                "-algorithm",
                "RSA",
                "-pkeyopt",
                "rsa_keygen_bits:2048",
            ])
            .output()
            .expect("openssl is on PATH");
        assert!(
            generated.status.success(),
            "openssl could not generate a key: {}",
            String::from_utf8_lossy(&generated.stderr)
        );
        let private_pem = String::from_utf8(generated.stdout).expect("PEM is text");

        let mut reading = Command::new("openssl")
            .args(["rsa", "-noout", "-modulus"])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("openssl is on PATH");
        reading
            .stdin
            .take()
            .expect("stdin is piped")
            .write_all(private_pem.as_bytes())
            .expect("openssl reads the key");
        let read = reading.wait_with_output().expect("openssl finishes");
        assert!(
            read.status.success(),
            "openssl could not read the modulus: {}",
            String::from_utf8_lossy(&read.stderr)
        );
        let printed = String::from_utf8(read.stdout).expect("modulus is text");
        let hex = printed
            .trim()
            .strip_prefix("Modulus=")
            .expect("openssl prints Modulus=<hex>");
        let bytes: Vec<u8> = (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex digits"))
            .collect();

        Self {
            private_pem,
            modulus: URL_SAFE_NO_PAD.encode(bytes),
        }
    }

    /// This key as the JWK set publishes it, under `kid`.
    fn jwk(&self, kid: &str) -> Value {
        json!({
            "kty": "RSA",
            "alg": "RS256",
            "use": "sig",
            "kid": kid,
            "n": self.modulus,
            "e": "AQAB",
        })
    }

    /// `claims` signed with this key, naming `kid` in the header.
    fn mint(&self, kid: &str, claims: &Claims) -> String {
        let mut header = Header::new(Algorithm::RS256);
        header.kid = Some(kid.to_owned());
        let key = EncodingKey::from_rsa_pem(self.private_pem.as_bytes()).expect("RSA PEM");
        encode(&header, claims, &key).expect("token encodes")
    }
}

/// Assert `result` is the refusal for a kid the key set does not carry.
fn assert_unknown_kid<T>(result: Result<T, IamError>, kid: &str) {
    match result {
        Err(IamError::Rejected(why)) => assert!(
            why.contains(kid),
            "expected the refusal to name kid {kid}, got: {why}"
        ),
        Err(other) => panic!("expected Rejected for kid {kid}, got {other}"),
        Ok(_) => panic!("a token naming unknown kid {kid} must not verify"),
    }
}

#[tokio::test]
async fn unknown_kids_inside_the_interval_cost_one_fetch_between_them() {
    // Every token below names a kid the set does not carry, so each lookup
    // misses. Before the interval existed each miss forced a refetch (the first
    // one two), so twelve tokens were thirteen fetches from Google, sent before
    // anything about the token was checked.
    let signer = Signer::generate();
    let server = KeySetServer::start(&[signer.jwk("published-kid")]).await;
    let verifier = server.verifier(LONG_INTERVAL);
    let claims = Claims::for_caller();

    for attempt in 0..10 {
        let kid = format!("made-up-kid-{attempt}");
        assert_unknown_kid(verifier.verify(&signer.mint(&kid, &claims)).await, &kid);
    }
    // A repeat offender is refused from memory too.
    for _ in 0..2 {
        assert_unknown_kid(
            verifier
                .verify(&signer.mint("made-up-kid-0", &claims))
                .await,
            "made-up-kid-0",
        );
    }

    assert_eq!(
        server.fetches(),
        1,
        "twelve unknown kids inside one interval must share the single fetch"
    );

    // The set that one fetch brought still verifies a token its kid names.
    let accepted = verifier
        .verify(&signer.mint("published-kid", &claims))
        .await
        .expect("a token naming the published kid verifies");
    assert_eq!(accepted.sub, "115000000000000000001");
    assert_eq!(server.fetches(), 1);
}

#[tokio::test]
async fn concurrent_misses_on_a_cold_cache_share_one_fetch() {
    let signer = Signer::generate();
    let server = KeySetServer::start(&[signer.jwk("published-kid")]).await;
    let verifier = Arc::new(server.verifier(LONG_INTERVAL));
    let claims = Claims::for_caller();
    let tokens: Vec<(String, String)> = (0..20)
        .map(|i| {
            let kid = format!("made-up-kid-{i}");
            let token = signer.mint(&kid, &claims);
            (kid, token)
        })
        .collect();

    let results = join_all(tokens.iter().map(|(_, token)| {
        let verifier = Arc::clone(&verifier);
        async move { verifier.verify(token).await }
    }))
    .await;

    for ((kid, _), result) in tokens.iter().zip(results) {
        assert_unknown_kid(result, kid);
    }
    assert_eq!(
        server.fetches(),
        1,
        "lookups that need a fetch at the same moment must wait for one, not start twenty"
    );
}

#[tokio::test]
async fn a_rotated_key_is_found_once_the_interval_has_passed() {
    let interval = Duration::from_millis(300);
    let old_key = Signer::generate();
    let new_key = Signer::generate();
    let server = KeySetServer::start(&[old_key.jwk("old-kid")]).await;
    let verifier = server.verifier(interval);
    let claims = Claims::for_caller();

    verifier
        .verify(&old_key.mint("old-kid", &claims))
        .await
        .expect("the published key verifies");
    assert_eq!(server.fetches(), 1);

    // Google publishes the next key beside the current one.
    server.publish(
        StatusCode::OK,
        json!({ "keys": [old_key.jwk("old-kid"), new_key.jwk("new-kid")] }).to_string(),
    );
    sleep(interval + Duration::from_millis(100)).await;

    let accepted = verifier
        .verify(&new_key.mint("new-kid", &claims))
        .await
        .expect("a kid first seen after the interval is fetched and found");
    assert_eq!(accepted.email.as_deref(), Some(CALLER));
    assert_eq!(server.fetches(), 2, "the new kid costs exactly one refetch");

    // Found once, it is served from the refreshed set.
    verifier
        .verify(&new_key.mint("new-kid", &claims))
        .await
        .expect("the new key keeps verifying");
    verifier
        .verify(&old_key.mint("old-kid", &claims))
        .await
        .expect("the old key is still published and still verifies");
    assert_eq!(server.fetches(), 2);
}

#[tokio::test]
async fn a_failing_key_set_endpoint_is_not_retried_per_request() {
    let signer = Signer::generate();
    let server = KeySetServer::start(&[]).await;
    server.publish(
        StatusCode::SERVICE_UNAVAILABLE,
        "<html>backend unavailable</html>".to_owned(),
    );
    let verifier = server.verifier(LONG_INTERVAL);
    let token = signer.mint("any-kid", &Claims::for_caller());

    for _ in 0..5 {
        match verifier.verify(&token).await {
            Err(IamError::JwksUnavailable(_)) => {}
            Err(other) => panic!("an unreachable key set is JwksUnavailable, got {other}"),
            Ok(_) => panic!("nothing can verify without a key set"),
        }
    }
    assert_eq!(
        server.fetches(),
        1,
        "a failed fetch starts the interval, like a successful one"
    );
}

#[tokio::test]
async fn an_allowlisted_caller_whose_email_google_did_not_verify_is_refused() {
    let signer = Signer::generate();
    let server = KeySetServer::start(&[signer.jwk("published-kid")]).await;
    let verifier = server.verifier(LONG_INTERVAL).allowing([CALLER]);

    let mut unverified = Claims::for_caller();
    unverified.email_verified = false;
    match verifier
        .verify(&signer.mint("published-kid", &unverified))
        .await
    {
        Err(IamError::Rejected(why)) => assert!(
            why.contains("verified"),
            "expected the refusal to name the unverified email, got: {why}"
        ),
        Err(other) => panic!("expected Rejected, got {other}"),
        Ok(_) => panic!("an unverified email must not pass the allowlist"),
    }

    let accepted = verifier
        .verify(&signer.mint("published-kid", &Claims::for_caller()))
        .await
        .expect("the same caller with a verified email is accepted");
    assert_eq!(accepted.email.as_deref(), Some(CALLER));
    assert_eq!(accepted.email_verified, Some(true));
}
